
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Scene
{
public sealed partial class SceneConfig : Luban.BeanBase
{
    public SceneConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Level = _buf.ReadString();
        AssetPath = _buf.ReadString();
        EntityGroupName = _buf.ReadString();
        Priority = _buf.ReadInt();
    }

    public static SceneConfig DeserializeSceneConfig(ByteBuf _buf)
    {
        return new Scene.SceneConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡
    /// </summary>
    public readonly string Level;
    /// <summary>
    /// 路径
    /// </summary>
    public readonly string AssetPath;
    /// <summary>
    /// 处于哪个组
    /// </summary>
    public readonly string EntityGroupName;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
   
    public const int __ID__ = -1765919668;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Level:" + Level + ","
        + "AssetPath:" + AssetPath + ","
        + "EntityGroupName:" + EntityGroupName + ","
        + "Priority:" + Priority + ","
        + "}";
    }
}
}

