
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Scene
{
public partial class TbSceneConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Scene.SceneConfig> _dataMap;
    private readonly System.Collections.Generic.List<Scene.SceneConfig> _dataList;
    
    public TbSceneConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Scene.SceneConfig>(n);
        _dataList = new System.Collections.Generic.List<Scene.SceneConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Scene.SceneConfig _v;
            _v = global::GameConfig.Scene.SceneConfig.DeserializeSceneConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Scene.SceneConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Scene.SceneConfig> DataList => _dataList;

    public Scene.SceneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Scene.SceneConfig Get(int key) => _dataMap[key];
    public Scene.SceneConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

