
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Actor
{
public sealed partial class ActorConfig : Luban.BeanBase
{
    public ActorConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EntityId = (Entity.EntityId)_buf.ReadInt();
        MoveSpeed = _buf.ReadFloat();
    }

    public static ActorConfig DeserializeActorConfig(ByteBuf _buf)
    {
        return new Actor.ActorConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 实体名称
    /// </summary>
    public readonly Entity.EntityId EntityId;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
   
    public const int __ID__ = 2091716318;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "EntityId:" + EntityId + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "}";
    }
}
}

