
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Actor
{
public partial class TbActorConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Actor.ActorConfig> _dataMap;
    private readonly System.Collections.Generic.List<Actor.ActorConfig> _dataList;
    
    public TbActorConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Actor.ActorConfig>(n);
        _dataList = new System.Collections.Generic.List<Actor.ActorConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Actor.ActorConfig _v;
            _v = global::GameConfig.Actor.ActorConfig.DeserializeActorConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Actor.ActorConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Actor.ActorConfig> DataList => _dataList;

    public Actor.ActorConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Actor.ActorConfig Get(int key) => _dataMap[key];
    public Actor.ActorConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

