//------------------------------------------------------------
// Resources Collection Constant
// Auto-generated by GameFrameworkTopMenu plugin.
// Do not modify manually.
// Generation time: 2026-09-03 22:28:48
//------------------------------------------------------------

namespace GameConfig.Constant
{
	public static class ResourcesCollectionConstant
{
		public const string Audios_AudioBundle = "res://TheGame/Audios/AudioBundle.tres";
		public const string Audios_AudioBus = "res://TheGame/Audios/AudioBus.tres";
		public const string Music_Menu = "res://TheGame/Audios/Music/Menu.wav";
		public const string Music_musiс = "res://TheGame/Audios/Music/musiс.wav";
		public const string Sounds_ability_popup = "res://TheGame/Audios/Sounds/ability_popup.wav";
		public const string Sounds_bomb = "res://TheGame/Audios/Sounds/bomb.wav";
		public const string Sounds_chest_opening = "res://TheGame/Audios/Sounds/chest_opening.wav";
		public const string Sounds_chest_spawn = "res://TheGame/Audios/Sounds/chest_spawn.wav";
		public const string Sounds_chest = "res://TheGame/Audios/Sounds/chest.wav";
		public const string Sounds_click = "res://TheGame/Audios/Sounds/click.wav";
		public const string Sounds_coin = "res://TheGame/Audios/Sounds/coin.wav";
		public const string Sounds_complete = "res://TheGame/Audios/Sounds/complete.wav";
		public const string Sounds_damage_taken = "res://TheGame/Audios/Sounds/damage_taken.wav";
		public const string Sounds_failure = "res://TheGame/Audios/Sounds/failure.wav";
		public const string Sounds_gem_ring = "res://TheGame/Audios/Sounds/gem_ring.wav";
		public const string Sounds_heal = "res://TheGame/Audios/Sounds/heal.wav";
		public const string Sounds_hit_pop = "res://TheGame/Audios/Sounds/hit_pop.wav";
		public const string Sounds_level_up = "res://TheGame/Audios/Sounds/level_up.wav";
		public const string Sounds_magnet = "res://TheGame/Audios/Sounds/magnet.wav";
		public const string Sounds_revive = "res://TheGame/Audios/Sounds/revive.wav";
		public const string DataTables_DataTableBundle = "res://TheGame/DataTables/DataTableBundle.tres";
		public const string GameConfigs_entity_tbentityconfig = "res://TheGame/DataTables/GameConfigs/entity_tbentityconfig.bytes";
		public const string GameConfigs_ui_tbuiformconfig = "res://TheGame/DataTables/GameConfigs/ui_tbuiformconfig.bytes";
		public const string Localizations_ChineseSimplified = "res://TheGame/DataTables/Localizations/ChineseSimplified.txt";
		public const string Localizations_English = "res://TheGame/DataTables/Localizations/English.txt";
		public const string Entitys_EntityBundle = "res://TheGame/Entitys/EntityBundle.tres";
		public const string Fonts_simhei = "res://TheGame/MainPack/Fonts/simhei.ttf";
		public const string Resources_ArchiveSetting = "res://TheGame/MainPack/Resources/ArchiveSetting.tres";
		public const string Resources_EntityGroupRes = "res://TheGame/MainPack/Resources/EntityGroupRes.tres";
		public const string Resources_NodePoolConfigRes = "res://TheGame/MainPack/Resources/NodePoolConfigRes.tres";
		public const string Resources_ScriptGenerateRes = "res://TheGame/MainPack/Resources/ScriptGenerateRes.tres";
		public const string Resources_SoundGroupRes = "res://TheGame/MainPack/Resources/SoundGroupRes.tres";
		public const string Resources_UIGroupRes = "res://TheGame/MainPack/Resources/UIGroupRes.tres";
		public const string Resources_UpdateSettingRes = "res://TheGame/MainPack/Resources/UpdateSettingRes.tres";
		public const string Themes_MainThemes = "res://TheGame/MainPack/Themes/MainThemes.tres";
		public const string UI_LoadingForm = "res://TheGame/MainPack/UI/LoadingForm.tscn";
		public const string UI_QuestionTips = "res://TheGame/MainPack/UI/QuestionTips.tscn";
		public const string Scenes_LevelMap_1 = "res://TheGame/Scenes/LevelMap_1.tscn";
		public const string Scenes_ScenesBundle = "res://TheGame/Scenes/ScenesBundle.tres";
		public const string Enemy_enemy_bug = "res://TheGame/Sprites/Characters/Enemy/enemy_bug.png";
		public const string Enemy_enemy_crab = "res://TheGame/Sprites/Characters/Enemy/enemy_crab.png";
		public const string Enemy_enemy_fire_slime = "res://TheGame/Sprites/Characters/Enemy/enemy_fire_slime.png";
		public const string Enemy_enemy_queen_shooting = "res://TheGame/Sprites/Characters/Enemy/enemy_queen_shooting.png";
		public const string Enemy_enemy_queen_wasp = "res://TheGame/Sprites/Characters/Enemy/enemy_queen_wasp.png";
		public const string Player_wizard_defeat = "res://TheGame/Sprites/Characters/Player/wizard_defeat.png";
		public const string Player_wizard_idle = "res://TheGame/Sprites/Characters/Player/wizard_idle.png";
		public const string Player_wizard_revive = "res://TheGame/Sprites/Characters/Player/wizard_revive.png";
		public const string Player_wizard_walk_new = "res://TheGame/Sprites/Characters/Player/wizard_walk_new.png";
		public const string Sprites_SpritesBundle = "res://TheGame/Sprites/SpritesBundle.tres";
		public const string Stage_back_grass_darkest = "res://TheGame/Sprites/Stage/back_grass_darkest.png";
		public const string Stage_back_stone = "res://TheGame/Sprites/Stage/back_stone.png";
		public const string UI_ui_ab_bean = "res://TheGame/Sprites/UI/ui_ab_bean.png";
		public const string UI_ui_button_background = "res://TheGame/Sprites/UI/ui_button_background.png";
		public const string UI_ui_button_blue = "res://TheGame/Sprites/UI/ui_button_blue.png";
		public const string UI_ui_button_brown = "res://TheGame/Sprites/UI/ui_button_brown.png";
		public const string UI_ui_button_gray = "res://TheGame/Sprites/UI/ui_button_gray.png";
		public const string UI_ui_button_green = "res://TheGame/Sprites/UI/ui_button_green.png";
		public const string UI_ui_button_purple = "res://TheGame/Sprites/UI/ui_button_purple.png";
		public const string UI_ui_button_red = "res://TheGame/Sprites/UI/ui_button_red.png";
		public const string UI_ui_button_yellow = "res://TheGame/Sprites/UI/ui_button_yellow.png";
		public const string UI_ui_coin_spin = "res://TheGame/Sprites/UI/ui_coin_spin.png";
		public const string UI_ui_item_background = "res://TheGame/Sprites/UI/ui_item_background.png";
		public const string UI_ui_menu_background_color_2 = "res://TheGame/Sprites/UI/ui_menu_background_color_2.png";
		public const string UI_ui_menu_background_color_3 = "res://TheGame/Sprites/UI/ui_menu_background_color_3.png";
		public const string UI_ui_menu_background_color = "res://TheGame/Sprites/UI/ui_menu_background_color.png";
		public const string UI_ui_menu_background_pattern_triangle = "res://TheGame/Sprites/UI/ui_menu_background_pattern_triangle.png";
		public const string UI_ui_menu_background_pattern = "res://TheGame/Sprites/UI/ui_menu_background_pattern.png";
		public const string UI_ui_panel_white = "res://TheGame/Sprites/UI/ui_panel_white.png";
		public const string UI_ui_pause = "res://TheGame/Sprites/UI/ui_pause.png";
		public const string UI_ui_progress_big_fill = "res://TheGame/Sprites/UI/ui_progress_big_fill.png";
		public const string UI_ui_progress_big = "res://TheGame/Sprites/UI/ui_progress_big.png";
		public const string UI_ui_progress_small_fill = "res://TheGame/Sprites/UI/ui_progress_small_fill.png";
		public const string UI_ui_progress_small = "res://TheGame/Sprites/UI/ui_progress_small.png";
		public const string UI_ui_settings = "res://TheGame/Sprites/UI/ui_settings.png";
		public const string UI_ui_toggle_off_old = "res://TheGame/Sprites/UI/ui_toggle_off_old.png";
		public const string UI_ui_toggle_off = "res://TheGame/Sprites/UI/ui_toggle_off.png";
		public const string UI_ui_toggle_on_old = "res://TheGame/Sprites/UI/ui_toggle_on_old.png";
		public const string UI_ui_toggle_on = "res://TheGame/Sprites/UI/ui_toggle_on.png";
		public const string UI_ui_window_background = "res://TheGame/Sprites/UI/ui_window_background.png";
		public const string VFX_RetroImpactEffectA = "res://TheGame/Sprites/VFX/RetroImpactEffectA.png";
		public const string VFX_ui_ab_wand = "res://TheGame/Sprites/VFX/ui_ab_wand.png";
		public const string VFX_vfx_dagger = "res://TheGame/Sprites/VFX/vfx_dagger.png";
		public const string VFX_vfx_lightning_ball_red = "res://TheGame/Sprites/VFX/vfx_lightning_ball_red.png";
		public const string VFX_vfx_star = "res://TheGame/Sprites/VFX/vfx_star.png";
		public const string VFX_vfx_sword_slash = "res://TheGame/Sprites/VFX/vfx_sword_slash.png";
		public const string VFX_vfx_wand_projectile = "res://TheGame/Sprites/VFX/vfx_wand_projectile.png";
		public const string UIs_MainForm = "res://TheGame/UIs/MainForm.tscn";
		public const string UIs_MenuForm = "res://TheGame/UIs/MenuForm.tscn";
		public const string UIs_SettingForm = "res://TheGame/UIs/SettingForm.tscn";
		public const string UIs_UIsBundle = "res://TheGame/UIs/UIsBundle.tres";
	}
}
